import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
      
        <div className="container max-w-screen-xl m-auto">
        <div className="flex justify-between flex-wrap py-10">
          <a href="/">Home</a>
          <a href="/products">Components</a>
          <a href="/state">Interactivity/State</a>
          <a href="/react-basics">React Basics</a>
        </div>
        {children}
        </div>
      </body>
    </html>
  );
}
